
import "./globals.css";
import Link from 'next/link'; 
import Image from 'next/image';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="es"
      className=""
    >
      <body className="min-h-full flex flex-col">
        {/* BARRA LATERAL (Sidebar) - Siempre visible */}
        <nav className="w-64 bg-rose-50 text-black p-6 flex flex-col gap-4">
          <h2 className="text-2xl font-bold mb-8 text-blue-400">H2-Vitoria: Gestión de Hidrógeno💧</h2>

          {/* Usamos <Link> para navegación instantánea */}
          <Link href="/" className="hover:text-blue-300 transition">Inicio</Link>
          <Link href="/línea-H2" className="hover:text-blue-300 transition">Línea H2</Link>
          <Link href="/seguridad" className="hover:text-blue-300 transition">Seguridad</Link>
        

          <div className="mt-auto text-xs text-slate-500">

            <Image
              width="100"
              height={100}
              src="https://images.unsplash.com/photo-1492724441997-5dc865305da7"
              alt='operario trabajando en la producción de un coche Mercedes'
              className="rounded-lg shadow-2xl w-sm"
            />
            Planta Vitoria-Gasteiz v2.0
          </div>
        </nav>

        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
